### ISSUE TITLE
Cannot import name App

### ISSUE THREAD

**Issue by sekhar0520** [pyopenapi/pyswagger#169]
This is my python file pyswagger.py

from pyswagger import App
App.create('http://petstore.swagger.io/v2/swagger.json')

when i run this file i'm getting this error

Traceback (most recent call last):
  File "pyswagger.py", line 1, in <module>
    from pyswagger import App
  File "/home/dev-sekhar/Work/2019/DART/OutofSpec-API/pyswagger.py", line 1, in <module>
    from pyswagger import App
ImportError: cannot import name App

I have installed pyswagger using 'pip install pyswagger' command, not able to find what is going wrong

**Comment by sekhar0520** [comment]
got the problem, i named pyswagger as the filename which is causing circular dependency
