### ISSUE TITLE
2 arguments needed in create function 

### ISSUE THREAD

**Issue by shivangi06** [pyopenapi/pyswagger#195]
Traceback (most recent call last):
  File "initialize.py", line 6, in <module>
    app = App._create_("/local/data/home/eqtdata/sandbox/khanshi/qfix_newone/rooster/swagger.json")
  File "/local/data/home/eqtdata/sandbox/khanshi/qfix_newone/rooster/pyswagger-develop/pyswagger/core.py", line 364, in create
    app = kls.load(url)
  File "/local/data/home/eqtdata/sandbox/khanshi/qfix_newone/rooster/pyswagger-develop/pyswagger/core.py", line 285, in load
    app.__raw, app.__version = app.load_obj(url, getter=getter, parser=parser)
  File "/local/data/home/eqtdata/sandbox/khanshi/qfix_newone/rooster/pyswagger-develop/pyswagger/core.py", line 166, in load_obj
    obj = self.__resolver.resolve(jref, getter)
  File "/local/data/home/eqtdata/sandbox/khanshi/qfix_newone/rooster/pyswagger-develop/pyswagger/resolve.py", line 62, in resolve
    obj = six.advance_iterator(getter)
  File "/local/data/home/eqtdata/sandbox/khanshi/qfix_newone/rooster/pyswagger-develop/pyswagger/getter.py", line 48, in __next__
    obj = yaml.load(obj)
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by shivangi06** [comment]
json file issue,closing it
